AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Quiz AI Lambda
Parameters:
  BranchName:
    Type: String
    Description: "Git branch name for environment-based function naming"
  GROQAPIKEY:
    Type: String
    Description: "API key for GROQ"
Globals:
  Function:
    Timeout: 900
    Runtime: provided.al2
Resources:
  GenerateQuestionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub freequizapp-${BranchName}
      Handler: bootstrap
      CodeUri: .
      Runtime: provided.al2
      Environment:
        Variables:
          GROQAPIKEY: !Ref GROQAPIKEY
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
  AllowBrowserInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GenerateQuestionsFunction
      Action: lambda:InvokeFunctionUrl
      Principal: "*"
      FunctionUrlAuthType: NONE
