AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Quiz AI Lambda
Parameters:
  GROQAPIKEY: ${{ secrets.GROQAPIKEY }}
Globals:
  Function:
    Timeout: 900
    Runtime: provided.al2
Resources:
  GenerateQuestionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: freequizapp-generate
      Handler: bootstrap
      CodeUri: .
      Runtime: provided.al2
      Environment:
        Variables:
          GROQAPIKEY: !Ref GROQAPIKEY
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM
