name: Backend CI/CD (Go + SAM)

on:
  push:
    branches: [main]  # same branch connected in Amplify for frontend

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-1  # update if needed
      STACK_NAME: freequizapp
      S3_BUCKET: acme-goapp-prod-samdeploy-us-west-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run Go tests
        working-directory: backend
        run: go test ./...

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build SAM app
        working-directory: backend
        run: sam build

      - name: Deploy SAM app
        working-directory: backend
        run: |
          sam deploy \
            --stack-name ${{ env.STACK_NAME }} \
            --s3-bucket ${{ env.S3_BUCKET }} \
            --capabilities CAPABILITY_IAM \
            --region ${{ env.AWS_REGION }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
